#!/bin/bash
# ===========================================
# ThaliumX Backup Automation Setup
# ===========================================
# This script sets up automated backups using cron
# Backups run daily at 2 AM by default
#
# Usage:
#   ./setup-backup-cron.sh [install|uninstall|status]
# ===========================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_SCRIPT="${SCRIPT_DIR}/backup-all.sh"
BACKUP_DIR="${BACKUP_DIR:-/opt/thaliumx/backups}"
LOG_DIR="${LOG_DIR:-/var/log/thaliumx}"
CRON_SCHEDULE="${CRON_SCHEDULE:-0 2 * * *}"  # Daily at 2 AM

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Cron job identifier
CRON_ID="# ThaliumX Automated Backup"

show_usage() {
    echo "Usage: $0 [install|uninstall|status|test]"
    echo ""
    echo "Commands:"
    echo "  install   - Install backup cron job"
    echo "  uninstall - Remove backup cron job"
    echo "  status    - Show current backup configuration"
    echo "  test      - Run a test backup"
    echo ""
    echo "Environment Variables:"
    echo "  BACKUP_DIR     - Backup destination (default: /opt/thaliumx/backups)"
    echo "  LOG_DIR        - Log directory (default: /var/log/thaliumx)"
    echo "  CRON_SCHEDULE  - Cron schedule (default: '0 2 * * *' = daily at 2 AM)"
    echo ""
    echo "Examples:"
    echo "  $0 install                           # Install with defaults"
    echo "  CRON_SCHEDULE='0 */6 * * *' $0 install  # Every 6 hours"
}

install_cron() {
    echo -e "${BLUE}=== Installing ThaliumX Backup Cron Job ===${NC}"
    echo ""
    
    # Create directories
    echo "Creating directories..."
    sudo mkdir -p "${BACKUP_DIR}"
    sudo mkdir -p "${LOG_DIR}"
    sudo chown -R $(whoami):$(whoami) "${BACKUP_DIR}"
    sudo chown -R $(whoami):$(whoami) "${LOG_DIR}"
    
    # Make backup script executable
    chmod +x "${BACKUP_SCRIPT}"
    
    # Create wrapper script with logging
    WRAPPER_SCRIPT="${SCRIPT_DIR}/backup-cron-wrapper.sh"
    cat > "${WRAPPER_SCRIPT}" << EOF
#!/bin/bash
# ThaliumX Backup Cron Wrapper
# Auto-generated by setup-backup-cron.sh

TIMESTAMP=\$(date +%Y%m%d_%H%M%S)
LOG_FILE="${LOG_DIR}/backup_\${TIMESTAMP}.log"

echo "=== ThaliumX Backup Started: \$(date) ===" >> "\${LOG_FILE}"

# Run backup
BACKUP_BASE_DIR="${BACKUP_DIR}" ${BACKUP_SCRIPT} >> "\${LOG_FILE}" 2>&1
RESULT=\$?

echo "=== ThaliumX Backup Completed: \$(date) ===" >> "\${LOG_FILE}"
echo "Exit Code: \${RESULT}" >> "\${LOG_FILE}"

# Rotate logs (keep last 30 days)
find "${LOG_DIR}" -name "backup_*.log" -mtime +30 -delete 2>/dev/null || true

# Send notification on failure (optional)
if [ \${RESULT} -ne 0 ]; then
    echo "Backup failed with exit code \${RESULT}" | logger -t thaliumx-backup
fi

exit \${RESULT}
EOF
    chmod +x "${WRAPPER_SCRIPT}"
    
    # Remove existing cron job if present
    (crontab -l 2>/dev/null | grep -v "${CRON_ID}" | grep -v "backup-cron-wrapper.sh") | crontab - 2>/dev/null || true
    
    # Add new cron job
    (crontab -l 2>/dev/null; echo "${CRON_ID}"; echo "${CRON_SCHEDULE} ${WRAPPER_SCRIPT}") | crontab -
    
    echo -e "${GREEN}✓ Cron job installed${NC}"
    echo ""
    echo "Configuration:"
    echo "  Schedule:    ${CRON_SCHEDULE}"
    echo "  Backup Dir:  ${BACKUP_DIR}"
    echo "  Log Dir:     ${LOG_DIR}"
    echo "  Script:      ${WRAPPER_SCRIPT}"
    echo ""
    echo "Current crontab:"
    crontab -l | grep -A1 "${CRON_ID}" || echo "  (none)"
}

uninstall_cron() {
    echo -e "${BLUE}=== Removing ThaliumX Backup Cron Job ===${NC}"
    echo ""
    
    # Remove cron job
    (crontab -l 2>/dev/null | grep -v "${CRON_ID}" | grep -v "backup-cron-wrapper.sh") | crontab - 2>/dev/null || true
    
    echo -e "${GREEN}✓ Cron job removed${NC}"
    echo ""
    echo "Note: Backup directory and logs were NOT deleted."
    echo "  Backup Dir: ${BACKUP_DIR}"
    echo "  Log Dir:    ${LOG_DIR}"
}

show_status() {
    echo -e "${BLUE}=== ThaliumX Backup Status ===${NC}"
    echo ""
    
    # Check cron job
    echo "Cron Job:"
    if crontab -l 2>/dev/null | grep -q "backup-cron-wrapper.sh"; then
        echo -e "  Status: ${GREEN}Installed${NC}"
        crontab -l | grep -A1 "${CRON_ID}" | sed 's/^/  /'
    else
        echo -e "  Status: ${YELLOW}Not installed${NC}"
    fi
    echo ""
    
    # Check backup directory
    echo "Backup Directory: ${BACKUP_DIR}"
    if [ -d "${BACKUP_DIR}" ]; then
        BACKUP_COUNT=$(find "${BACKUP_DIR}" -name "thaliumx_backup_*.tar.gz" 2>/dev/null | wc -l)
        BACKUP_SIZE=$(du -sh "${BACKUP_DIR}" 2>/dev/null | cut -f1)
        echo "  Backups: ${BACKUP_COUNT}"
        echo "  Total Size: ${BACKUP_SIZE}"
        echo ""
        echo "  Recent Backups:"
        ls -lht "${BACKUP_DIR}"/thaliumx_backup_*.tar.gz 2>/dev/null | head -5 | sed 's/^/    /' || echo "    (none)"
    else
        echo -e "  ${YELLOW}Directory does not exist${NC}"
    fi
    echo ""
    
    # Check logs
    echo "Log Directory: ${LOG_DIR}"
    if [ -d "${LOG_DIR}" ]; then
        LOG_COUNT=$(find "${LOG_DIR}" -name "backup_*.log" 2>/dev/null | wc -l)
        echo "  Log Files: ${LOG_COUNT}"
        echo ""
        echo "  Recent Logs:"
        ls -lht "${LOG_DIR}"/backup_*.log 2>/dev/null | head -5 | sed 's/^/    /' || echo "    (none)"
        
        # Show last backup result
        LAST_LOG=$(ls -t "${LOG_DIR}"/backup_*.log 2>/dev/null | head -1)
        if [ -n "${LAST_LOG}" ]; then
            echo ""
            echo "  Last Backup Result:"
            tail -3 "${LAST_LOG}" | sed 's/^/    /'
        fi
    else
        echo -e "  ${YELLOW}Directory does not exist${NC}"
    fi
}

test_backup() {
    echo -e "${BLUE}=== Running Test Backup ===${NC}"
    echo ""
    
    # Create directories if needed
    mkdir -p "${BACKUP_DIR}"
    mkdir -p "${LOG_DIR}"
    
    # Run backup
    BACKUP_BASE_DIR="${BACKUP_DIR}" "${BACKUP_SCRIPT}"
    
    echo ""
    echo -e "${GREEN}✓ Test backup complete${NC}"
}

# Main
case "${1:-}" in
    install)
        install_cron
        ;;
    uninstall)
        uninstall_cron
        ;;
    status)
        show_status
        ;;
    test)
        test_backup
        ;;
    *)
        show_usage
        exit 1
        ;;
esac