"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
const google_1 = require("next/font/google");
require("./globals.css");
const geistSans = (0, google_1.Geist)({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const geistMono = (0, google_1.Geist_Mono)({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
exports.metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
function RootLayout({ children, }) {
    return (<html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="p-4 flex justify-between items-center border-b">
          <div className="font-semibold">ThaliumX</div>
          <div className="flex gap-3 items-center">
            {/* Keycloak auth and wallet connect buttons */}
            {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
            <a className="text-sm underline" href="/portfolio">Portfolio</a>
            <div id="auth-placeholder"></div>
          </div>
        </div>
        <div className="p-4">{children}</div>
      </body>
    </html>);
}
//# sourceMappingURL=layout.js.map