import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="p-4 flex justify-between items-center border-b">
          <div className="font-semibold">ThaliumX</div>
          <div className="flex gap-3 items-center">
            {/* Keycloak auth and wallet connect buttons */}
            {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
            <a className="text-sm underline" href="/portfolio">Portfolio</a>
            <div id="auth-placeholder"></div>
          </div>
        </div>
        <div className="p-4">{children}</div>
      </body>
    </html>
  );
}
