apisix:
  id: "thaliumx-apisix"
  allow_update_config: false
  node_listen: 9080
  enable_ipv6: false
  ssl:
    listen_port: 9443
    ssl_certificate: /tmp/certs/server.crt
    ssl_certificate_key: /tmp/certs/server.key
    ssl_protocols: "TLSv1.2 TLSv1.3"
  enable_admin: true
  admin_listen:
    ip: 0.0.0.0
    port: 9180
  admin_key:
    - name: admin
      key: c8f7ecfcfdc37ce3e566569839160ac1315f827d3675653c73048c2631a93440
      role: admin

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

routes:
  - id: 1
    uri: /*
    host: thaliumx.com
    upstream:
      nodes:
        thaliumx-backend:3002: 1
      type: roundrobin
  - id: 2
    uri: /*
    host: auth.thaliumx.com
    upstream:
      nodes:
        thaliumx-authentik:9000: 1
      type: roundrobin
  - id: 3
    uri: /*
    priority: 10
    upstream:
      nodes:
        thaliumx-frontend:3000: 1
      type: roundrobin
  - id: 4
    uri: /graphql
    methods: ["GET", "POST"]
    enable_websocket: true
    upstream:
      nodes:
        thaliumx-graphql:4000: 1
      type: roundrobin
    plugins:
      openid-connect:
        client_id: ${AUTHENTIK_CLIENT_ID}
        client_secret: ${AUTHENTIK_CLIENT_SECRET}
        discovery: https://thaliumx.com/application/o/thaliumx/.well-known/openid-configuration
        redirect_uri: https://thaliumx.com/graphql/auth/callback
        scope: openid profile email
        session:
          secret: ${APISIX_SESSION_SECRET}
  - id: 5
    uri: /support/chat/*
    upstream:
      nodes:
        thaliumx-live-helper-chat:80: 1
      type: roundrobin
    plugins:
      openid-connect:
        client_id: ${AUTHENTIK_CLIENT_ID}
        client_secret: ${AUTHENTIK_CLIENT_SECRET}
        discovery: https://thaliumx.com/application/o/thaliumx/.well-known/openid-configuration
        redirect_uri: https://thaliumx.com/support/chat/auth/callback
        scope: openid profile email
        session:
          secret: ${APISIX_SESSION_SECRET}
  - id: 6
    uri: /support/tickets/*
    upstream:
      nodes:
        thaliumx-osticket:80: 1
      type: roundrobin
    plugins:
      openid-connect:
        client_id: ${AUTHENTIK_CLIENT_ID}
        client_secret: ${AUTHENTIK_CLIENT_SECRET}
        discovery: https://thaliumx.com/application/o/thaliumx/.well-known/openid-configuration
        redirect_uri: https://thaliumx.com/support/tickets/auth/callback
        scope: openid profile email
        session:
          secret: ${APISIX_SESSION_SECRET}

upstreams: []
